version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"      # Port MQTT
      - "9001:9001"      # Port WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - iot_network
      - dokploy-network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    container_name: iot_simulator_web
    ports:
      - "5000:5000"
    environment:
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - iot_network
      - dokploy-network
    volumes:
      - ./templates:/app/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot-simulator.rule=Host(`iot.benamara.tn`)"
      - "traefik.http.routers.iot-simulator.entrypoints=websecure"
      - "traefik.http.routers.iot-simulator.tls=true"
      - "traefik.http.routers.iot-simulator.tls.certresolver=letsencrypt"
      - "traefik.http.services.iot-simulator.loadbalancer.server.port=5000"
      - "traefik.docker.network=dokploy-network"

networks:
  iot_network:
    driver: bridge
  dokploy-network:
    external: true
